/**
 * Generate a markdown file with front-matter
 *
 * @param {Object} options - Options for the post
 * @param {string} options.title - Post title
 * @param {string} [options.date] - ISO date string (defaults to now)
 * @param {string[]} [options.tags] - List of tags
 * @param {string[]} [options.categories] - List of categories
 * @param {string} [options.body] - Content of the markdown body
 * @returns {{ content: string, filename: string }} The generated markdown content and filename
 */
function generateMarkdownPost({
  title,
  date = new Date().toISOString(),
  tags = [],
  categories = [],
  body = 'This is a test post generated by script.'
}) {
  const frontMatter =
    `---\n` +
    `title: "${title}"\n` +
    `date: ${date}\n` +
    `tags: [${tags.map((tag) => `"${tag}"`).join(', ')}]\n` +
    `categories: [${categories.map((cat) => `"${cat}"`).join(', ')}]\n` +
    `---\n\n`;

  const content = frontMatter + body + '\n';

  const filenameSlug = title
    .toLowerCase()
    .replace(/[^\w]+/g, '-')
    .replace(/^-|-$/g, '');
  const filename = `${date.split('T')[0]}-${filenameSlug}.md`;
  return { content, filename };
}

/**
 * Runs a shell command with live output
 * @param {string} command - The command to run
 * @param {string[]} [args=[]] - Arguments for the command
 * @param {object} [options={}] - Options for spawn
 * @returns {Promise<void>} Resolves when the command completes successfully
 */
function runCommand(command, args = [], options = {}) {
  const { spawn } = require('cross-spawn');
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: 'inherit',
      shell: true,
      ...options
    });

    child.on('error', reject);

    child.on('close', (code) => {
      if (code !== 0) {
        return reject(new Error(`Command failed: ${command} ${args.join(' ')}`));
      }
      resolve();
    });
  });
}

module.exports = {
  generateMarkdownPost,
  runCommand
};
