const { spawn } = require('cross-spawn');
const fs = require('fs-extra');
const path = require('upath');

/**
 * Generate a markdown file with front-matter
 *
 * @param {Object} options - Options for the post
 * @param {string} options.title - Post title
 * @param {string} [options.date] - ISO date string (defaults to now)
 * @param {string[]} [options.tags] - List of tags
 * @param {string[]} [options.categories] - List of categories
 * @param {string} [options.body] - Content of the markdown body
 * @returns {{ content: string, filename: string }} The generated markdown content and filename
 */
function generateMarkdownPost({
  title,
  date = new Date().toISOString(),
  tags = [],
  categories = [],
  body = 'This is a test post generated by script.'
}) {
  const frontMatter =
    `---\n` +
    `title: "${title}"\n` +
    `date: ${date}\n` +
    `tags: [${tags.map((tag) => `"${tag}"`).join(', ')}]\n` +
    `categories: [${categories.map((cat) => `"${cat}"`).join(', ')}]\n` +
    `---\n\n`;

  const content = frontMatter + body + '\n';

  const filenameSlug = title
    .toLowerCase()
    .replace(/[^\w]+/g, '-')
    .replace(/^-|-$/g, '');
  const filename = `${date.split('T')[0]}-${filenameSlug}.md`;
  return { content, filename };
}

/**
 * Runs a shell command with live output
 * @param {string} command - The command to run
 * @param {string[]} [args=[]] - Arguments for the command
 * @param {import('child_process').SpawnOptions} [options={}] - Options for spawn
 * @returns {Promise<void>} Resolves when the command completes successfully
 */
function runCommand(command, args = [], options = {}) {
  return new Promise((resolve, reject) => {
    // If stdio is not inherit, capture output for error reporting
    const stdio = options.stdio || 'inherit';
    let stdout = '';
    let stderr = '';
    const spawnOpts = {
      shell: true,
      ...options,
      stdio: stdio === 'inherit' ? 'inherit' : ['ignore', 'pipe', 'pipe']
    };
    const child = spawn(command, args, spawnOpts);

    if (spawnOpts.stdio !== 'inherit') {
      if (child.stdout)
        child.stdout.on('data', (data) => {
          stdout += data.toString();
        });
      if (child.stderr)
        child.stderr.on('data', (data) => {
          stderr += data.toString();
        });
    }

    child.on('error', reject);

    child.on('close', (code) => {
      if (code !== 0) {
        let msg = `Command failed: ${command} ${args.join(' ')}`;
        if (spawnOpts.stdio !== 'inherit') {
          if (stdout) msg += `\nstdout:\n${stdout}`;
          if (stderr) msg += `\nstderr:\n${stderr}`;
        }
        return reject(new Error(msg));
      }
      resolve();
    });
  });
}

/**
 * Create multiple random markdown posts with randomized tags and categories
 * @param {string} dir - Directory to write posts
 * @param {number} count - Number of posts to generate
 * @param {string[]} tagsList - List of possible tags
 * @param {string[]} categoriesList - List of possible categories
 * @returns {string[]} Array of generated filenames
 */
function generateRandomMarkdownPosts(dir, count = 1, tagsList = ['test'], categoriesList = ['default']) {
  const filenames = [];
  for (let i = 0; i < count; i++) {
    const title = `Test Post ${Math.floor(Math.random() * 10000)}`;
    const date = new Date(Date.now() - Math.floor(Math.random() * 100000000)).toISOString();
    const tags = tagsList
      .sort(() => 0.5 - Math.random())
      .slice(0, Math.max(1, Math.floor(Math.random() * tagsList.length) + 1));
    const categories = categoriesList
      .sort(() => 0.5 - Math.random())
      .slice(0, Math.max(1, Math.floor(Math.random() * categoriesList.length) + 1));
    const { content, filename } = generateMarkdownPost({
      title,
      date,
      tags,
      categories,
      body: 'This is a random test post for Hexo.'
    });
    fs.ensureDirSync(dir);
    fs.writeFileSync(path.join(dir, filename), content, 'utf8');
    filenames.push(filename);
  }
  return filenames;
}

module.exports = {
  generateMarkdownPost,
  runCommand,
  generateRandomMarkdownPosts
};
