version: '3.8'
# docker-compose -f docker-compose.test.yml up --abort-on-container-exit
# Use the following commands to run tests in different Node.js versions
# docker-compose -f docker-compose.test.yml run --rm node18
# docker-compose -f docker-compose.test.yml run --rm node20
# docker-compose -f docker-compose.test.yml run --rm node22
services:
  node18:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - node18_modules:/app/node_modules
      - node18_dist:/app/dist
      - node18_tmp:/app/tmp
      - node18_yarnlock:/app/yarn.lock
    command: sh -c "touch yarn.lock && yarn install && npm test -- normal"
  node20:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - node20_modules:/app/node_modules
      - node20_dist:/app/dist
      - node20_tmp:/app/tmp
      - node20_yarnlock:/app/yarn.lock
    command: sh -c "touch yarn.lock && yarn install && npm test -- normal"
  node22:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      - node22_modules:/app/node_modules
      - node22_dist:/app/dist
      - node22_tmp:/app/tmp
      - node22_yarnlock:/app/yarn.lock
    command: sh -c "touch yarn.lock && yarn install && npm test -- normal"

volumes:
  node18_modules:
  node20_modules:
  node22_modules:
  node18_dist:
  node20_dist:
  node22_dist:
  node18_tmp:
  node20_tmp:
  node22_tmp:
  node18_yarnlock:
  node20_yarnlock:
  node22_yarnlock:
