name: Build Master Branch

on:
  push:
    branches: [ compiler ]
  #pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ compiler ]

# cancel previous workflows, run only one workflow
concurrency:
  group: build-master-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set TimeZone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: "compiler"
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm i -g npm gulp-cli typescript hexo-cli 
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - run: npm install
      - run: npm run build
        id: build
      - run: ls docs
      - run: |
          cp dist docs/
          cp .eslintrc docs/
          cp .eslintignore docs/
          cp LICENSE docs/
          cp package.json docs/
          cp package-lock.json docs/
      - name: Deploy Master Branch 🚀
        if: steps.build.outcome == 'success' && steps.build.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          token: "${{ secrets.GITHUB_TOKEN }}"
          commit-message: GitFlow Deploy 🚀 ${{ steps.date.outputs.date }}
