name: Test Demo

on: [push, pull_request]

jobs:
  internal:
    name: Using Direct Files
    runs-on: ubuntu-latest
    steps:
      - name: Set TimeZone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Jakarta'
          timezoneMacos: 'Asia/Jakarta'
          timezoneWindows: 'Indonesia Standard Time'
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          ref: monorepo
          submodules: recursive
          token: '${{ secrets.GITHUB_TOKEN }}'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: update submodules
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
          echo "disable githooks warning"
          git config advice.ignoredHook false
        shell: bash
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm i -g npm gulp-cli typescript hexo-cli
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - run: npm install
      - run: cd test && npm i ./../ && npm update hexo-seo
      - run: cd test && hexo generate

  git:
    if: ${{ false }} # disable for now cause git cache error
    name: Using GitHub Package
    runs-on: ubuntu-latest
    steps:
      - name: Set TimeZone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Jakarta'
          timezoneMacos: 'Asia/Jakarta'
          timezoneWindows: 'Indonesia Standard Time'
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: monorepo
          token: '${{ secrets.GITHUB_TOKEN }}'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i -g npm gulp-cli typescript hexo-cli
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm install
      - run: cd test && npm install 'dimaslanjaka/hexo-seo#master' && npm update hexo-seo
      - run: cd test && hexo generate

  npm:
    name: Using NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Set TimeZone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Jakarta'
          timezoneMacos: 'Asia/Jakarta'
          timezoneWindows: 'Indonesia Standard Time'
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: monorepo
          token: '${{ secrets.GITHUB_TOKEN }}'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i -g npm gulp-cli typescript hexo-cli
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - run: npm install
      - run: cd test && npm i hexo-seo && npm update hexo-seo
      - run: cd test && hexo generate
